- hosts: openwrt
  roles:
    - gekmihesg.openwrt
  tasks:
    - name: ping
      ping:
    # - name: copy openwrt image
    #   command: "{{ openwrt_scp }}" image.bin {{ openwrt_user_host|quote }}:/tmp/sysupgrade.bin"
    #   delegate_to: localhost
    # - name: start sysupgrade
    #   nohup:
    #     command: sysupgrade -q /tmp/sysupgrade.bin
    # - name: wait for reboot
    #   wait_for_connection:
    #     timeout: 300
    #     delay: 60
    # - name: install mdns
    #   opkg:
    #     name: mdns
    #     state: present
    # - name: enable and start mdns
    #   service:
    #     name: mdns
    #     state: started
    #     enabled: yes
    # - name: copy authorized keys
    #   copy:
    #     src: authorized_keys
    #     dest: /etc/dropbear/authorized_keys
    # - name: revert pending changes
    #   uci:
    #     command: revert
    # - name: configure wifi device radio0
    #   uci:
    #     command: set
    #     key: wireless.radio0
    #     value:
    #       phy: phy0
    #       type: mac80211
    #       hwmode: 11g
    #       channel: auto
    # - name: configure wifi interface
    #   uci:
    #     command: section
    #     config: wireless
    #     type: wifi-iface
    #     find_by:
    #       device: radio0
    #       mode: ap
    #     value:
    #       ssid: MySSID
    #       encryption: psk2+ccmp
    #       key: very secret
    # - name: commit changes
    #   uci:
    #     command: commit
    #   notify: reload wifi

